name: Build and Deploy

on:
  push:
    branches:
      - main
      
permissions:
  contents: read
  pages: write
  id-token: write
  
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install and Build
        run: |
          npm i
          npm run build

      - name: Deploy
        run: |
          npm i -g surge
          surge ./dist ${{ secrets.SURGE_DOMAIN }} --token ${{ secrets.SURGE_TOKEN }}
